### ISSUE TITLE
请问WS2812的NDK驱动可以开源吗？

### ISSUE THREAD

**Issue by superlonger** [liujiaqi7998/QiPortableLabel_V5#1]
最近也在学习air724的lua开发，发现无法直接驱动ws2812，看到你实现了nkd库，想学习一下源码。

**Comment by superlonger** [comment]
而且你的代码也有BUG，无法显示红色。LED数量也不能设置。

**Comment by liujiaqi7998** [comment]
学业繁忙，不好意思，没有及时回复，回去我传一下ndk代码，某一颜色不能正常显示的原因是ndk所支持的延时，无法达到ws2812标准，因为ndk并非真正的底层逻辑，要想达到ns级别延时，唯一的方法就是，多次执行同一语句，因为单条语句的执行就已经能达到15ns了，这导致了传输过程中会有信号失效，从而出现某一颜色多次显示后才能达到想要的效果这个bug，非常希望合宇官方人员看到后可以优化性的问题，或解决部分单总线协议问题。

**Comment by liujiaqi7998** [comment]
当然仍然可以使用spi来解决这个问题

**Comment by superlonger** [comment]
> 

spi也不好使，发送数据时，会随机出现延迟，导致颜色显示不正常。一般发10次，可能会有1-2次颜色错误。

**Comment by liujiaqi7998** [comment]
https://github.com/liujiaqi7998/Air724-NDK-ws2812b
有BUG，要精确显示建议多次调用

**Comment by superlonger** [comment]
谢谢分享，我其实也已经实现了跟你类似的NDK驱动，方案也是一样的，通过多次调用set_gpio来实现的，开始用了while循环，但是后面发现不怎么有用，就改成多次调用set_gpio了。
但是还是一样有问题，偶尔会出现灯乱跳的情况。

666小奇 ***@***.***> 于2023年8月31日周四 18:40写道：
